### ISSUE TITLE
Missing a default .env file?

### ISSUE THREAD

**Issue by liu-jc** [SalesforceAIResearch/uni2ts#1]
I think we may need to provide a default empty .env file? Otherwise, if we run `from uni2ts.eval_util.data import get_gluonts_test_dataset` in the example, we will face the problem about "cannot find the .env file". To increase the usability.
![image](https://github.com/SalesforceAIResearch/uni2ts/assets/17921248/b98dcb5b-3e88-4889-880d-225ac7ae6053)

**Comment by abdulmeral** [comment]
hello, 
i couldnt build from source also..
![image](https://github.com/SalesforceAIResearch/uni2ts/assets/63063646/eb5df53d-74b0-46ab-affd-2a985b808156)

**Comment by liu-jc** [comment]
> hello, i couldnt build from source also.. ![image](https://private-user-images.githubusercontent.com/63063646/315284143-eb5df53d-74b0-46ab-affd-2a985b808156.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzM0ODIsIm5iZiI6MTcxMTAzMzE4MiwicGF0aCI6Ii82MzA2MzY0Ni8zMTUyODQxNDMtZWI1ZGY1M2QtNzRiMC00NmFiLWFmZmQtMmE5ODViODA4MTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE0NTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MDVmNjAzMDMxZDdiN2U5NDc3N2ZiZTk3Y2MwMmFjMzc3MDRmZjFmNWQyZTE4YzVhNDBkYzcyMmE3YmVlYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3qFQACplbBIL1RVYtdvEBPH_8t5rt3I12m3Mc0xY0OM)

Hi @abdulmeral,
Could you provide all the command lines you used for building the environment?

**Comment by Reyosss** [comment]
> hello, i couldnt build from source also.. ![image](https://private-user-images.githubusercontent.com/63063646/315284143-eb5df53d-74b0-46ab-affd-2a985b808156.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzU2NTEsIm5iZiI6MTcxMTMzNTM1MSwicGF0aCI6Ii82MzA2MzY0Ni8zMTUyODQxNDMtZWI1ZGY1M2QtNzRiMC00NmFiLWFmZmQtMmE5ODViODA4MTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDAyNTU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ODhkMjI3YjU5ZTZhYWU1ZmI1YTliNzc3ODFhMDc3YmMwZmFiYTg3Yzg0OWMyN2VkODQ3Nzg5ZGVmMjg5NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0mBTtwoxnOJD6_vNd-LhLV0TbSXUVESabJiInZzN2mo)

Hi @abdulmeral,i'm facing the same problem, did you solved this problem?

**Comment by gorold** [comment]
Hi @abdulmeral, @Reyosss, could you provide more details for us to replicate the error? e.g. what is your set up, what commands did you enter, etc.

**Comment by Reyosss** [comment]
> Hi @abdulmeral, @Reyosss, could you provide more details for us to replicate the error? e.g. what is your set up, what commands did you enter, etc.

![截图](https://github.com/SalesforceAIResearch/uni2ts/assets/61939428/1d5c6b3f-5d9a-4ebc-961d-fbabc101e499)
after creating virtual environment in win10, i can not build from source, it's saying "'.[notebook]' is not a valid editable requirement", but i couldn't find a requirement file in this project, how can i solve this problem, thx!!!

**Comment by gorold** [comment]
@Reyosss you need to call `pip install -e '.[notebook]'` in the `uni2ts` folder

**Comment by Reyosss** [comment]
@gorold 
![image](https://github.com/SalesforceAIResearch/uni2ts/assets/61939428/843ac58e-26a1-4c0d-8340-d8e7fed4658c)
still the same error

**Comment by gorold** [comment]
It might be the quotation marks on windows? could you try without quotation marks or with double quotation marks?

**Comment by Reyosss** [comment]
> It might be the quotation marks on windows? could you try without quotation marks or with double quotation marks?

nice, i call `pip install -e .[notebook] in win10`,dependency now can be downloaded, thx!!!

**Comment by gorold** [comment]
I've updated the installation instructions to specify the creation of a `.env` file -- this should solve the issue.

**Comment by abdulmeral** [comment]
thank you guys, it worked for me too, you are great.
