### ISSUE TITLE
Installing uni2ts from PyPI gives a ModuleNotFoundError

### ISSUE THREAD

**Issue by ConstantinaNicolaou** [SalesforceAIResearch/uni2ts#117]
**Describe the bug**
I am experiencing a `ModuleNotFoundError` when attempting to import the package after installation from PyPI. The package appears to install (without error), but it cannot be imported. Other packages in the same environment are working fine.

**To Reproduce**
Install with PyPI, then do
```python
import uni2ts
```

**Expected behavior**
The package should import without errors after installation.

**Error message or code output**
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'uni2ts'
```

**Environment**
* Operating system: macOS 14.6.1
* Python version: 3.10.13
* PyTorch version: 2.4.0
* uni2ts version (have you pulled the latest version?): 1.1.0

**Additional comments**
Installing `uni2ts` from source works fine.
I am installing `uni2ts` using poetry by specifying it as a dependency in the `pyproject.toml` file. I am able to import dependencies required by `uni2ts` but not `uni2ts` itself.

Thank you in advance for your help.

**Comment by liu-jc** [comment]
Hi @ConstantinaNicolaou,

Could you try again? We found an issue in our previous package on pypi. I just test it and now it should be fine.

**Comment by ConstantinaNicolaou** [comment]
Thank you @liu-jc for fixing this so quickly. I can confirm it now works as expected.
