### ISSUE TITLE
Upgrade release version

### ISSUE THREAD

**Issue by Otsutsukii** [SalesforceAIResearch/uni2ts#145]
Hello, thanks for releasing the model and code. 

But could you please upgrade the release version that include MOIRAI-MOE 

( For pip install )

**Comment by liu-jc** [comment]
Hi @Otsutsukii ,

Thanks for this issue. We will do it in these two weeks. Will update the status here

**Comment by liu-jc** [comment]
Hi @Otsutsukii 

We have uploaded the latest version 1.2.0 to PyPI. Please check it out :)
