### ISSUE TITLE
era5_2005 missed in the public lotsa_data

### ISSUE THREAD

**Issue by HALF111** [SalesforceAIResearch/uni2ts#15]
It seems that era5_2005 is missed in the public lotsa_data (https://huggingface.co/datasets/Salesforce/lotsa_data/tree/main) accidentally. 
Maybe it is necessary to supplement it later. Thanks!
<img width="743" alt="98e2ffa4a95abd0f695d837e53236bb" src="https://github.com/SalesforceAIResearch/uni2ts/assets/58055693/be3688d3-42a8-4de0-a3d3-79f2d93b9ecf">

**Comment by gorold** [comment]
Thanks for catching this, it's been uploaded!
