### ISSUE TITLE
Clarification on prediction_mask in MoiraiFinetune

### ISSUE THREAD

**Issue by zqiao11** [SalesforceAIResearch/uni2ts#29]
Hi @gorold. May I clarify the setup of [the prediction mask](https://github.com/SalesforceAIResearch/uni2ts/blob/main/src/uni2ts/model/moirai/finetune.py#L452) in validation dataset in MoiraiFinetune? 

```
            + EvalMaskedPrediction(
                mask_length=-prediction_length % patch_size,  # num of patches for prediction?
                target_field="target",
                truncate_fields=("variate_id", "time_id", "observed_mask"),
                optional_truncate_fields=("past_feat_dynamic_real",),
                prediction_mask_field="prediction_mask",
                expected_ndim=3,
            )
```

Now `mask_length` is computed as `-prediction_length % patch_size`. Shouldn't the `mask_length` be computed as `prediction_length // patch_size`? As the logic [here](https://github.com/SalesforceAIResearch/uni2ts/blob/main/src/uni2ts/transform/task.py#L143) seems to mask the patches in the prediction range.

```
    def _generate_prediction_mask(
        self, target: Float[np.ndarray, "var time *feat"]
    ) -> Bool[np.ndarray, "var time"]:
        self.check_ndim("target", target, self.expected_ndim)
        var, time = target.shape[:2]
        prediction_mask = np.zeros((var, time), dtype=bool)
        prediction_mask[:, -self.mask_length :] = True
        return prediction_mask
```

Please correct me if my understanding is incorrect. Look forward to your reply.

**Comment by gorold** [comment]
I think there wouldn't be a difference if the prediction range is already padded?

**Comment by zqiao11** [comment]
Let's say if prediction length is 96 and patch size if 64, the prediction range will be padded to 128 to make sure there are multiple patches. So, the last 2 patches should be masked as True in `prediction_mask`. 

If we use `prediction_length // patch_size`, then only the last patch is marked as True.

**Comment by gorold** [comment]
Right... this makes sense. Thanks a lot!
