### ISSUE TITLE
Embeddings from MOIRAI

### ISSUE THREAD

**Issue by thisthq** [SalesforceAIResearch/uni2ts#32]
Hi,

I would like to know how to extract embeddings of the last hidden state to capture embeddings from your model.

Regards,
thq

**Comment by gorold** [comment]
We currently don't support this function out of the box, but you can extract the representations from this line: https://github.com/SalesforceAIResearch/uni2ts/blob/ce27c2f9a0c6ee9119997e8ef0026388f143dcd6/src/uni2ts/model/moirai/module.py#L108
