### ISSUE TITLE
Can this model be used with exogenous data ? 

### ISSUE THREAD

**Issue by simoRancati** [SalesforceAIResearch/uni2ts#33]
Hi, 
I am trying to use your model with exogenous variables following the "Multivariate" example. is it possible to use Moirai with exogenous variables ? 
thanks in advance

**Comment by gorold** [comment]
There's an example here now https://github.com/SalesforceAIResearch/uni2ts/blob/exogenous/example/moirai_forecast_pandas.ipynb
