### ISSUE TITLE
Finetuning bug

### ISSUE THREAD

**Issue by wyhzunzun123123** [SalesforceAIResearch/uni2ts#38]
Hello, I really appreciate your work as it got such a surprising performance in zero-shot setting. But I‘ve gotten a problem while fine-tuning using your command 'python -m cli.finetune run_name=example_run model=moirai_1.0_R_small data=etth1 val_data=etth1'. 
The specific bug is 'UserWarning: resource_tracker: There appear to be 12 leaked semaphore objects to clean up at shutdown warnings.warn('resource_tracker: There appear to be %d ''.
Although I tried so many methods provided by the internet, this issue still can't be addressed. Could you give some advice?

**Comment by gorold** [comment]
I think you can ignore this, seems like some issue with the dataloading.
