### ISSUE TITLE
How to load the local pre-trained checkpoint and then fine-tune with the dataset

### ISSUE THREAD

**Issue by FrankHo-Hwc** [SalesforceAIResearch/uni2ts#84]
**Is your feature request related to a problem? Please describe.**
I face the problem of loading the local huggingface checkpoint to fine-tune on the etth1. I have to download the model weights because our GPU nodes can't reach the huggingface.  So do how I load the local checkpoint and then fine-tune it? Thanks a lot!

**Comment by gorold** [comment]
https://github.com/SalesforceAIResearch/uni2ts/blob/main/cli/conf/finetune/model/moirai_1.0_R_small.yaml

https://github.com/SalesforceAIResearch/uni2ts/blob/main/cli/conf/finetune/model/moirai_small.yaml

Please see these 2 files, depending if you want to load the huggingface_hub file or the lightning checkpoint.

**Comment by FrankHo-Hwc** [comment]
> https://github.com/SalesforceAIResearch/uni2ts/blob/main/cli/conf/finetune/model/moirai_1.0_R_small.yaml
> 
> https://github.com/SalesforceAIResearch/uni2ts/blob/main/cli/conf/finetune/model/moirai_small.yaml
> 
> Please see these 2 files, depending if you want to load the huggingface_hub file or the lightning checkpoint.

Thanks for the help, I have solved the problem.
