### ISSUE TITLE
Release uni2ts on PyPI

### ISSUE THREAD

**Issue by pranavvp16** [SalesforceAIResearch/uni2ts#90]
Currently users have to install uni2ts from source, this makes it difficult to install in CI, currently I see a release tag on github i.e 1.1.0 releasing this version of PyPi, would help users to a great extent

**Comment by liu-jc** [comment]
Hi @pranavvp16, 

Thanks for the suggestion! We will put this into our plan and hopefully do it soon.

**Comment by dany4142** [comment]
I will second this, please help with. this. thanks

**Comment by liu-jc** [comment]
Hi @pranavvp16 @dany4142,

We have uploaded the package to PyPi. You can find it here https://pypi.org/project/uni2ts/1.1.0/. Please check it out :)

**Comment by dany4142** [comment]
It does not work all, after installing it says no module uni2ts

**Comment by liu-jc** [comment]
Hi @dany4142, when did you try this? Could you try again now? Maybe clear the cache first, for example, `pip cache remove uni2ts`.  I thought a similar issue was resolved: https://github.com/SalesforceAIResearch/uni2ts/issues/117#issuecomment-2321814272

Feel free to let me know it still doesn't work.
