### ISSUE TITLE
Bug on custom dataset

### ISSUE THREAD

**Issue by qingyuanxingsi** [SalesforceAIResearch/uni2ts#98]
**Describe the bug**
I construct a dataset with size **50000*6(feat_dim)*48(context length)**, finetune meeting the following error:
**To Reproduce**
Please provide a code snippet of a minimal reproducible example for the error. 
```python
/root/miniconda3/envs/llm_ts/bin/python3 -m cli.train -cp conf/finetune run_name=demo_run model=moirai_1.0_R_small data=feed_train val_data=feed_eval
```

**Expected behavior**

**Error message or code output**
Paste the complete error message, including stack trace, or the undesired output that the above snippet produces.
```shell
AssertionError: no valid patch size candidates for time series shape: (6, 48), freq: H, patch_sizes: [8, 16, 32, 64, 128], constraints: range(32, 33), min_time_patches: 2, patch_size_ceil: 24
```

**Environment**
* Operating system:
* Python version:
* PyTorch version:
* uni2ts version (have you pulled the latest version?)

**Comment by chenghaoliu89** [comment]
The length of each training sample is required to be longer than min_time_patches (2). Here the patch size range is (32, 33), which indicates the training sample should be longer than 64. Your data (48 length) does not satisfy this constraints.

One quick fix is to modify the DEFAULT_RANGES in `patch.py` to `"H": (1, 64),`

**Comment by hahne0922** [comment]
> **Describe the bug** A clear and concise description of what the bug is. I construct a dataset with size **50000*6(feat_dim)*48(context length)**, finetune meeting the following error: **To Reproduce** Please provide a code snippet of a minimal reproducible example for the error.
> 
> ```python
> /root/miniconda3/envs/llm_ts/bin/python3 -m cli.train -cp conf/finetune run_name=demo_run model=moirai_1.0_R_small data=feed_train val_data=feed_eval
> ```
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Error message or code output** Paste the complete error message, including stack trace, or the undesired output that the above snippet produces.
> 
> ```shell
> AssertionError: no valid patch size candidates for time series shape: (6, 48), freq: H, patch_sizes: [8, 16, 32, 64, 128], constraints: range(32, 33), min_time_patches: 2, patch_size_ceil: 24
> ```
> 
> **Environment**
> 
> * Operating system:
> * Python version:
> * PyTorch version:
> * uni2ts version (have you pulled the latest version?)



> `patch.py` to `"H": (1, 64),`

Have you solved this problem? I modified "H": (1, 64), "T": (1, 128) in patch.py, and the same error message appears.

**Comment by chenghaoliu89** [comment]
Hi @qingyuanxingsi do you have any further questions? If not, i will close this issue
